# Generated by Django 3.0.1 on 2020-01-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200101_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
